export default [
  // Drives
  {
    "length": 5,
    "isReinforced": false,
    "name": "FM200 Drive",
    "cost": 10,
    "integrityFunctioningThreshold": 50,
    "height": 5,
    "damageThreshold": 40,
    "integrity": 250,
    "width": 3,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM200 Drive",
    "cost": 10,
  },
  {
    "length": 5,
    "isReinforced": true,
    "name": "FM200R Drive",
    "cost": 20,
    "integrityFunctioningThreshold": 25,
    "height": 5,
    "damageThreshold": 60,
    "integrity": 500,
    "width": 3,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM200R Drive",
    "cost": 20,
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "FM230 'Whiplash' Drive",
    "cost": 20,
    "integrityFunctioningThreshold": 50,
    "height": 5,
    "damageThreshold": 40,
    "integrity": 250,
    "width": 3,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM230 'Whiplash' Drive",
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "FM240 'Dragonfly' Drive",
    "cost": 20,
    "integrityFunctioningThreshold": 50,
    "height": 5,
    "damageThreshold": 40,
    "integrity": 250,
    "width": 3,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM240 'Dragonfly' Drive",
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "FM280 'Raider' Drive",
    "cost": 20,
    "integrityFunctioningThreshold": 50,
    "height": 5,
    "damageThreshold": 40,
    "integrity": 250,
    "width": 3,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM280 'Raider' Drive",
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "FM30X 'Prowler' Drive",
    "cost": 25,
    "integrityFunctioningThreshold": 30,
    "height": 5,
    "damageThreshold": 25,
    "integrity": 200,
    "width": 3,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM30X 'Prowler' Drive",
  },
  {
    "length": 10,
    "isReinforced": false,
    "name": "FM500 Drive",
    "cost": 15,
    "integrityFunctioningThreshold": 50,
    "height": 10,
    "damageThreshold": 70,
    "integrity": 1000,
    "width": 8,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM500 Drive",
  },
  {
    "length": 10,
    "isReinforced": true,
    "name": "FM500R Drive",
    "cost": 30,
    "integrityFunctioningThreshold": 50,
    "height": 10,
    "damageThreshold": 80,
    "integrity": 1500,
    "width": 8,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM500R Drive",
  },
  {
    "length": 10,
    "isReinforced": false,
    "name": "FM530 'Whiplash' Drive",
    "cost": 30,
    "integrityFunctioningThreshold": 50,
    "height": 10,
    "damageThreshold": 70,
    "integrity": 1000,
    "width": 8,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM530 'Whiplash' Drive",
  },
  {
    "length": 10,
    "isReinforced": false,
    "name": "FM540 'Dragonfly' Drive",
    "cost": 30,
    "integrityFunctioningThreshold": 50,
    "height": 10,
    "damageThreshold": 70,
    "integrity": 1000,
    "width": 8,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM540 'Dragonfly' Drive",
  },
  {
    "length": 10,
    "isReinforced": false,
    "name": "FM580 'Raider' Drive",
    "cost": 30,
    "integrityFunctioningThreshold": 50,
    "height": 10,
    "damageThreshold": 70,
    "integrity": 1000,
    "width": 8,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FM580 'Raider' Drive",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Reinforced Thruster Nozzles",
    "cost": 10,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 50,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Reinforced Thruster Nozzles",
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "BW800 Drive",
    "cost": 10,
    "integrityFunctioningThreshold": 50,
    "height": 3,
    "damageThreshold": 40,
    "integrity": 250,
    "width": 5,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "BW800-R Drive",
    "cost": 20,
    "integrityFunctioningThreshold": 50,
    "height": 3,
    "damageThreshold": 50,
    "integrity": 500,
    "width": 5,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 12,
    "isReinforced": false,
    "name": "BW1500 Drive",
    "cost": 10,
    "integrityFunctioningThreshold": 50,
    "height": 12,
    "damageThreshold": 40,
    "integrity": 700,
    "width": 12,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 12,
    "isReinforced": false,
    "name": "BW1500-R Drive",
    "cost": 10,
    "integrityFunctioningThreshold": 50,
    "height": 12,
    "damageThreshold": 70,
    "integrity": 1400,
    "width": 12,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 12,
    "isReinforced": false,
    "name": "BW2000 Drive",
    "cost": 15,
    "integrityFunctioningThreshold": 50,
    "height": 12,
    "damageThreshold": 40,
    "integrity": 700,
    "width": 12,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "Sundrive Racing Pro",
    "cost": 30,
    "integrityFunctioningThreshold": 50,
    "height": 3,
    "damageThreshold": 30,
    "integrity": 100,
    "width": 5,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "CHI-777 Yard Drive",
    "cost": 20,
    "integrityFunctioningThreshold": 50,
    "height": 3,
    "damageThreshold": 40,
    "integrity": 250,
    "width": 5,
    "type": "module",
    "factions": [ "OSP" ],
    "key": "Stock/CHI-777 Yard Drive",
  },
  {
    "length": 12,
    "isReinforced": false,
    "name": "CHI-7700 Drive",
    "cost": 20,
    "integrityFunctioningThreshold": 50,
    "height": 12,
    "damageThreshold": 40,
    "integrity": 700,
    "width": 12,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 12,
    "isReinforced": false,
    "name": "CHI-9100 'Long Haul' Drive",
    "cost": 20,
    "integrityFunctioningThreshold": 50,
    "height": 12,
    "damageThreshold": 40,
    "integrity": 700,
    "width": 12,
    "type": "module",
    "factions": [ "OSP" ],
  },

  // Command and Intelligence
  {
    "length": 6,
    "isReinforced": false,
    "name": "Basic CIC",
    "cost": 10,
    "compounding": (number) => {
      if (number === 1) {
        return 1;
      }
      return (number - 1);
    },
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 25,
    "integrity": 200,
    "width": 4,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Basic CIC",
  },
  {
    "length": 6,
    "isReinforced": true,
    "name": "Reinforced CIC",
    "cost": 25,
    "compounding": (number) => {
      if (number === 1) {
        return 1;
      }
      return (number - 1);
    },
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 40,
    "integrity": 200,
    "width": 4,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Reinforced CIC",
  },
  {
    "length": 8,
    "isReinforced": true,
    "name": "Citadel CIC",
    "cost": 75,
    "compounding": (number) => {
      return (number - 1);
    },
    "integrityFunctioningThreshold": 20,
    "height": 1,
    "damageThreshold": 50,
    "integrity": 400,
    "width": 6,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Citadel CIC",
  },
  {
    "length": 3,
    "isReinforced": true,
    "name": "Auxiliary Steering",
    "cost": 10,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 20,
    "integrity": 300,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Auxiliary Steering",
  },
  {
    "length": 8,
    "isReinforced": false,
    "name": "Intelligence Center",
    "cost": 90,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 200,
    "width": 6,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Intelligence Center",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Analysis Annex",
    "cost": 20,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 10,
    "integrity": 100,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Analysis Annex",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "ES32 'Scryer' Missile ID System",
    "cost": 10,
    "integrityFunctioningThreshold": 15,
    "height": 2,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/ES32 'Scryer' Missile ID System",
  },

  // Guns
  {
    "length": 3,
    "isReinforced": false,
    "name": "Mk61 Cannon",
    "cost": 10,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk61 Cannon",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Mk62 Cannon",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk62 Cannon",
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "Mk64 Cannon",
    "cost": 30,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 20,
    "integrity": 225,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk64 Cannon",
  },
  {
    "length": 6,
    "isReinforced": false,
    "name": "Mk65 Cannon",
    "cost": 40,
    "integrityFunctioningThreshold": 15,
    "height": 4,
    "damageThreshold": 30,
    "integrity": 325,
    "width": 6,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk65 Cannon",
  },
  {
    "length": 6,
    "isReinforced": false,
    "name": "Mk66 Cannon",
    "cost": 45,
    "integrityFunctioningThreshold": 30,
    "height": 3,
    "damageThreshold": 30,
    "integrity": 350,
    "width": 6,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk66 Cannon",
  },
  {
    "length": 8,
    "isReinforced": false,
    "name": "Mk68 Cannon",
    "cost": 75,
    "integrityFunctioningThreshold": 30,
    "height": 5,
    "damageThreshold": 30,
    "integrity": 450,
    "width": 8,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk68 Cannon",
  },
  {
    "length": 6,
    "isReinforced": false,
    "name": "Mk81 Railgun",
    "cost": 50,
    "integrityFunctioningThreshold": 30,
    "height": 3,
    "damageThreshold": 30,
    "integrity": 300,
    "width": 6,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk81 Railgun",
  },
  {
    "length": 12,
    "isReinforced": false,
    "name": "Mk550 Mass Driver",
    "cost": 75,
    "integrityFunctioningThreshold": 20,
    "height": 4,
    "damageThreshold": 40,
    "integrity": 450,
    "width": 4,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk550 Mass Driver",
  },
  {
    "length": 12,
    "isReinforced": false,
    "name": "Mk600 Beam Cannon",
    "cost": 75,
    "integrityFunctioningThreshold": 20,
    "height": 4,
    "damageThreshold": 50,
    "integrity": 450,
    "width": 4,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk600 Beam Cannon",
  },
  {
    "length": 8,
    "isReinforced": false,
    "name": "Mk610 Beam Turret",
    "cost": 80,
    "integrityFunctioningThreshold": 30,
    "height": 5,
    "damageThreshold": 30,
    "integrity": 400,
    "width": 8,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk610 Beam Turret",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Ammunition Elevators",
    "cost": 20,
    "integrityFunctioningThreshold": 15,
    "height": 2,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Ammunition Elevators",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Rapid-Cycle Cradle",
    "cost": 20,
    "integrityFunctioningThreshold": 15,
    "height": 3,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 3,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Rapid-Cycle Cradle",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Energy Regulator",
    "cost": 30,
    "integrityFunctioningThreshold": 15,
    "height": 3,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 3,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Energy Regulator",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Focused Particle Accelerator",
    "cost": 25,
    "integrityFunctioningThreshold": 15,
    "height": 3,
    "damageThreshold": 40,
    "integrity": 150,
    "width": 3,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Focused Particle Accelerator",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Gun Plotting Center",
    "cost": 30,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 10,
    "integrity": 100,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Gun Plotting Center",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Mount Gyros",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 40,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Mount Gyros",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Small Energy Regulator",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 75,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Small Energy Regulator",
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "C30 Cannon",
    "cost": 15,
    "integrityFunctioningThreshold": 15,
    "height": 2,
    "damageThreshold": 40,
    "integrity": 350,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 4,
    "isReinforced": false,
    "name": "C53 Cannon",
    "cost": 15,
    "integrityFunctioningThreshold": 15,
    "height": 2,
    "damageThreshold": 40,
    "integrity": 350,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "C60 Cannon",
    "cost": 20,
    "integrityFunctioningThreshold": 30,
    "height": 3,
    "damageThreshold": 40,
    "integrity": 350,
    "width": 3,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 10,
    "isReinforced": false,
    "name": "C65 Cannon",
    "cost": 40,
    "integrityFunctioningThreshold": 20,
    "height": 6,
    "damageThreshold": 40,
    "integrity": 500,
    "width": 6,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 10,
    "isReinforced": false,
    "name": "C81 Cannon",
    "cost": 30,
    "integrityFunctioningThreshold": 20,
    "height": 6,
    "damageThreshold": 40,
    "integrity": 500,
    "width": 6,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 10,
    "isReinforced": false,
    "name": "TE45 Cannon",
    "cost": 100,
    "integrityFunctioningThreshold": 20,
    "height": 4,
    "damageThreshold": 40,
    "integrity": 450,
    "width": 4,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "T20 Cannon",
    "cost": 10,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 3,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 6,
    "isReinforced": false,
    "name": "T30 Cannon",
    "cost": 30,
    "integrityFunctioningThreshold": 10,
    "height": 3,
    "damageThreshold": 15,
    "integrity": 200,
    "width": 6,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 6,
    "isReinforced": false,
    "name": "T81 Cannon",
    "cost": 45,
    "integrityFunctioningThreshold": 10,
    "height": 3,
    "damageThreshold": 15,
    "integrity": 300,
    "width": 6,
    "type": "mount",
    "factions": [ "OSP" ],
  },

  // Power
  {
    "length": 5,
    "isReinforced": false,
    "name": "FR4800 Reactor",
    "cost": 10,
    "integrityFunctioningThreshold": 50,
    "height": 5,
    "damageThreshold": 40,
    "integrity": 300,
    "width": 5,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FR4800 Reactor",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "FR3300 Micro Reactor",
    "cost": 10,
    "integrityFunctioningThreshold": 50,
    "height": 3,
    "damageThreshold": 30,
    "integrity": 200,
    "width": 3,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/FR3300 Micro Reactor",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Small Reactor Booster",
    "cost": 10,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 40,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Small Reactor Booster",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Plant Control Center",
    "cost": 25,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 10,
    "integrity": 100,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Plant Control Center",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Redundant Reactor Failsafes",
    "cost": 25,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 75,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Redundant Reactor Failsafes",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Light Civilian Reactor",
    "cost": 10,
    "integrityFunctioningThreshold": 50,
    "height": 3,
    "damageThreshold": 30,
    "integrity": 200,
    "width": 3,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "Civilian Reactor",
    "cost": 10,
    "integrityFunctioningThreshold": 50,
    "height": 5,
    "damageThreshold": 40,
    "integrity": 300,
    "width": 5,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "Boosted Reactor",
    "cost": 10,
    "integrityFunctioningThreshold": 50,
    "height": 5,
    "damageThreshold": 40,
    "integrity": 300,
    "width": 5,
    "type": "module",
    "factions": [ "OSP" ],
    "key": "Stock/Boosted Reactor",
  },

  // Magazines
  {
    "length": 1,
    "isReinforced": true,
    "name": "Reinforced Magazine",
    "cost": (length, width, height) => {
      return length * width * height * 2;
    },
    "compounding": (number) => {
      if (number === 1) {
        return 0;
      }
      return 1;
    },
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 40,
    "integrity": 150,
    "width": 1,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Reinforced Magazine",
    "componentData": "BulkMagazineData",
  },
  {
    "length": 1,
    "isReinforced": false,
    "name": "Bulk Magazine",
    "cost": (length, width, height) => {
      return length * width * height;
    },
    "compounding": (number) => {
      if (number === 1) {
        return 0;
      }
      return 1;
    },
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 25,
    "integrity": 100,
    "width": 1,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Bulk Magazine",
    "componentData": "BulkMagazineData",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Magazine Sprinklers",
    "cost": 15,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 75,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Magazine Sprinklers",
  },

  // Radar
  {
    "length": 2,
    "isReinforced": false,
    "name": "RS35 'Frontline' Radar",
    "cost": 10,
    "integrityFunctioningThreshold": 30,
    "height": 2,
    "damageThreshold": 30,
    "integrity": 200,
    "width": 2,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/RS35 'Frontline' Radar",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "RS41 'Spyglass' Radar",
    "cost": 25,
    "integrityFunctioningThreshold": 30,
    "height": 2,
    "damageThreshold": 30,
    "integrity": 200,
    "width": 2,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/RS41 'Spyglass' Radar",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "RM50 'Parallax' Radar",
    "cost": 45,
    "integrityFunctioningThreshold": 30,
    "height": 2,
    "damageThreshold": 40,
    "integrity": 300,
    "width": 2,
    "type": "module",
    "factions": [ "ANS" ],
    "key": "Stock/RM50 'Parallax' Radar",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Adaptive Radar Receiver",
    "cost": 30,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 40,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Adaptive Radar Receiver",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Track Correlator",
    "cost": 25,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 40,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Track Correlator",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Strobe Correlator",
    "cost": 25,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 40,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Strobe Correlator",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "ES22 'Pinard' Electronic Support Module",
    "cost": 30,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 50,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/ES22 'Pinard' Electronic Support Module",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "RF101 'Bullseye' Radar",
    "cost": 40,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 10,
    "integrity": 70,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/RF101 'Bullseye' Radar",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Ithaca Bridgemaster",
    "cost": 10,
    "integrityFunctioningThreshold": 30,
    "height": 2,
    "damageThreshold": 30,
    "integrity": 200,
    "width": 2,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Bulwark Huntress",
    "cost": 20,
    "integrityFunctioningThreshold": 30,
    "height": 2,
    "damageThreshold": 30,
    "integrity": 200,
    "width": 2,
    "type": "module",
    "factions": [ "OSP" ],
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "R400 'Bloodhound' LRT Radar",
    "cost": 40,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 15,
    "integrity": 200,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
    "key": "Stock/R400 Radar",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "R550 Early Warning Radar",
    "cost": 65,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 3,
    "type": "mount",
    "factions": [ "OSP" ],
    "key": "Stock/R550 Early Warning Radar",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "RF44 'Pinpoint' Radar",
    "cost": 10,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 10,
    "integrity": 70,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },

  // Damage Control
  {
    "length": 3,
    "isReinforced": false,
    "name": "Rapid DC Locker",
    "cost": 10,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 70,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Rapid DC Locker",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Small DC Locker",
    "cost": 30,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Small DC Locker",
  },
  {
    "length": 6,
    "isReinforced": true,
    "name": "Reinforced DC Locker",
    "cost": 45,
    "integrityFunctioningThreshold": 20,
    "height": 1,
    "damageThreshold": 35,
    "integrity": 200,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Reinforced DC Locker",
  },
  {
    "length": 6,
    "isReinforced": false,
    "name": "Large DC Locker",
    "cost": 45,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Large DC Locker",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Damage Control Central",
    "cost": 20,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 35,
    "integrity": 200,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Damage Control Central",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Small Workshop",
    "cost": 20,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 35,
    "integrity": 150,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Small Workshop",
  },
  {
    "length": 1,
    "isReinforced": false,
    "name": "Berthing",
    "cost": (length, width, height) => {
      return length * width * height;
    },
    "compounding": (number) => {
      if (number === 1) {
        return 0;
      }
      return 1;
    },
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 50,
    "width": 1,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Berthing",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Battle Dressing Station",
    "cost": 20,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 10,
    "integrity": 125,
    "width": 3,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Battle Dressing Station",
  },
  {
    "length": 6,
    "isReinforced": false,
    "name": "Large DC Storage",
    "cost": 45,
    "integrityFunctioningThreshold": 10,
    "height": 3,
    "damageThreshold": 15,
    "integrity": 300,
    "width": 6,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Large DC Storage",
  },

  // Comms
  {
    "length": 2,
    "isReinforced": false,
    "name": "CR10 Antenna",
    "cost": 5,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/CR10 Antenna",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "CR70 Antenna",
    "cost": 15,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 30,
    "integrity": 250,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/CR70 Antenna",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Supplementary Radio Amplifiers",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 40,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Supplementary Radio Amplifiers",
  },

  // EWAR
  {
    "length": 3,
    "isReinforced": false,
    "name": "E15 'Masquerade' Signature Booster",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/E15 'Masquerade' Signature Booster",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "E55 'Spotlight' Illuminator",
    "cost": 15,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 75,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/E55 'Spotlight' Illuminator",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "E57 'Floodlight' Illuminator",
    "cost": 15,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 75,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/E57 'Floodlight' Illuminator",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "E70 'Interruption' Jammer",
    "cost": 55,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/E70 'Interruption' Jammer",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "E71 'Hangup' Jammer",
    "cost": 45,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 75,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/E71 'Hangup' Jammer",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "E90 'Blanket' Jammer",
    "cost": 50,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 75,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/E90 'Blanket' Jammer",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Signature Scrambler",
    "cost": 35,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 50,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Signature Scrambler",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Actively Cooled Amplifiers",
    "cost": 25,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 40,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Actively Cooled Amplifiers",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "L50 'Blackjack' Lazer Dazzler",
    "cost": 40,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 75,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "E20 'Lighthouse' Illuminator",
    "cost": 15,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 75,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "J360 'Lyrebird' Jammer",
    "cost": 100,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 3,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "J15 'Bellbird' Jammer",
    "cost": 50,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 3,
    "type": "mount",
    "factions": [ "OSP" ],
  },

  // PD
  {
    "length": 2,
    "isReinforced": false,
    "name": "Mk20 'Defender' PDT",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk20 'Defender' PDT",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Mk25 'Rebound' PDT",
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk25 'Rebound' PDT",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Mk29 'Stonewall' PDT",
    "cost": 40,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk29 'Stonewall' PDT",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Mk90 'Aurora' PDT",
    "cost": 55,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk90 'Aurora' PDT",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Mk95 'Sarissa' PDT",
    "cost": 65,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/Mk95 'Sarissa' PDT",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "P11 'Pavise' PDT",
    "cost": 15,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "P20 'Bastion' PDT",
    "cost": 15,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 150,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "P60 'Grazer' PDT",
    "cost": 35,
    "integrityFunctioningThreshold": 10,
    "height": 1,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },

  // Missiles
  {
    "length": 3,
    "isReinforced": false,
    "name": "MLS-2 Launcher",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 5,
    "isReinforced": false,
    "name": "MLS-3 Launcher",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "VLS1-23 Launcher",
    "cost": 5,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 15,
    "integrity": 75,
    "width": 2,
    "type": "mount",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/VLS-1-23 Launcher",
    "componentData": "CellLauncherData",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "VLS1-46 Launcher",
    "cost": 5,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 15,
    "integrity": 125,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/VLS-1-46 Launcher",
    "componentData": "CellLauncherData",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "VLS-2 Launcher",
    "cost": 10,
    "integrityFunctioningThreshold": 10,
    "height": 4,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/VLS-2 Launcher",
    "componentData": "CellLauncherData",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "VLS-3 Launcher",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 4,
    "damageThreshold": 15,
    "integrity": 175,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/VLS-3 Launcher",
    "componentData": "CellLauncherData",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "CLS-3 Launcher",
    "cost": 20,
    "integrityFunctioningThreshold": 10,
    "height": 4,
    "damageThreshold": 15,
    "integrity": 175,
    "width": 3,
    "type": "mount",
    "factions": [ "ANS" ],
    "key": "Stock/CLS-3 Launcher",
    "componentData": "CellLauncherData",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Launcher Deluge System",
    "cost": 15,
    "integrityFunctioningThreshold": 10,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 75,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Launcher Deluge System",
  },
  {
    "length": 8,
    "isReinforced": false,
    "name": "Strike Planning Center",
    "cost": 70,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 10,
    "integrity": 100,
    "width": 6,
    "type": "compartment",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Strike Planning Center",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "RL18 Launcher",
    "cost": 15,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 10,
    "integrity": 100,
    "width": 3,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 6,
    "isReinforced": false,
    "name": "RL36 Launcher",
    "cost": 15,
    "integrityFunctioningThreshold": 15,
    "height": 3,
    "damageThreshold": 10,
    "integrity": 175,
    "width": 6,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "ML-9 Mine Launcher",
    "cost": 10,
    "integrityFunctioningThreshold": 15,
    "height": 2,
    "damageThreshold": 10,
    "integrity": 175,
    "width": 3,
    "type": "mount",
    "factions": [ "OSP" ],
  },
  {
    "length": 6,
    "isReinforced": false,
    "name": "Container Stack Launcher",
    "cost": 5,
    "integrityFunctioningThreshold": 15,
    "height": 1,
    "damageThreshold": 10,
    "integrity": 200,
    "width": 6,
    "type": "mount",
    "factions": [ "OSP" ],
    "componentData": "CellLauncherData",
  },
  {
    "length": 20,
    "isReinforced": false,
    "name": "Container Bank Launcher",
    "cost": 5,
    "integrityFunctioningThreshold": 15,
    "height": 5,
    "damageThreshold": 10,
    "integrity": 500,
    "width": 10,
    "type": "mount",
    "factions": [ "OSP" ],
    "componentData": "CellLauncherData",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Missile Parallel Interface",
    "cost": 40,
    "integrityFunctioningThreshold": 15,
    "height": 2,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Missile Parallel Interface",
  },
  {
    "length": 2,
    "isReinforced": false,
    "name": "Missile Programming Bus",
    "cost": 30,
    "integrityFunctioningThreshold": 15,
    "height": 2,
    "damageThreshold": 15,
    "integrity": 80,
    "width": 2,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Missile Programming Bus",
  },
  {
    "length": 3,
    "isReinforced": false,
    "name": "Missile Programming Bus Array",
    "cost": 50,
    "integrityFunctioningThreshold": 15,
    "height": 3,
    "damageThreshold": 15,
    "integrity": 100,
    "width": 3,
    "type": "module",
    "factions": [ "ANS", "OSP" ],
    "key": "Stock/Missile Programming Bus Array",
  },
]
