export default [
    { "length": 10, "isReinforced": true, "name": "FM500R Drive", "integrityFunctioningThreshold": 50, "height": 10, "damageThreshold": 80, "integrity": 1500, "width": 8 },
    { "length": 10, "isReinforced": false, "name": "FM500 Drive", "integrityFunctioningThreshold": 50, "height": 10, "damageThreshold": 70, "integrity": 1000, "width": 8 },
    { "length": 10, "isReinforced": false, "name": "FM530 'Whiplash' Drive", "integrityFunctioningThreshold": 50, "height": 10, "damageThreshold": 70, "integrity": 1000, "width": 8 },
    { "length": 10, "isReinforced": false, "name": "FM540 'Dragonfly' Drive", "integrityFunctioningThreshold": 50, "height": 10, "damageThreshold": 70, "integrity": 1000, "width": 8 },
    { "length": 10, "isReinforced": false, "name": "FM580 'Raider' Drive", "integrityFunctioningThreshold": 50, "height": 10, "damageThreshold": 70, "integrity": 1000, "width": 8 },
    { "length": 5, "isReinforced": true, "name": "FM200R Drive", "integrityFunctioningThreshold": 25, "height": 5, "damageThreshold": 60, "integrity": 500, "width": 3 },
    { "length": 6, "isReinforced": true, "name": "Citadel CIC", "integrityFunctioningThreshold": 20, "height": 8, "damageThreshold": 50, "integrity": 400, "width": 1 },
    { "length": 4, "isReinforced": false, "name": "Mk600 Beam Cannon", "integrityFunctioningThreshold": 20, "height": 4, "damageThreshold": 50, "integrity": 450, "width": 12 },
    { "length": 5, "isReinforced": false, "name": "FM200 Drive", "integrityFunctioningThreshold": 50, "height": 5, "damageThreshold": 40, "integrity": 250, "width": 3 },
    { "length": 5, "isReinforced": false, "name": "FM230 'Whiplash' Drive", "integrityFunctioningThreshold": 50, "height": 5, "damageThreshold": 40, "integrity": 250, "width": 3 },
    { "length": 5, "isReinforced": false, "name": "FM240 'Dragonfly' Drive", "integrityFunctioningThreshold": 50, "height": 5, "damageThreshold": 40, "integrity": 250, "width": 3 },
    { "length": 5, "isReinforced": false, "name": "FM280 'Raider' Drive", "integrityFunctioningThreshold": 50, "height": 5, "damageThreshold": 40, "integrity": 250, "width": 3 },
    { "length": 3, "isReinforced": false, "name": "Focused Particle Accelerator", "integrityFunctioningThreshold": 15, "height": 3, "damageThreshold": 40, "integrity": 150, "width": 3 },
    { "length": 5, "isReinforced": false, "name": "FR4800 Reactor", "integrityFunctioningThreshold": 50, "height": 5, "damageThreshold": 40, "integrity": 300, "width": 5 },
    { "length": 4, "isReinforced": false, "name": "Mk550 Mass Driver", "integrityFunctioningThreshold": 20, "height": 4, "damageThreshold": 40, "integrity": 450, "width": 12 },
    { "length": 4, "isReinforced": true, "name": "Reinforced CIC", "integrityFunctioningThreshold": 10, "height": 6, "damageThreshold": 40, "integrity": 200, "width": 1 },
    { "length": 1, "isReinforced": true, "name": "Reinforced Magazine", "integrityFunctioningThreshold": 10, "height": 1, "damageThreshold": 40, "integrity": 150, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "RM50 'Parallax' Radar", "integrityFunctioningThreshold": 30, "height": 2, "damageThreshold": 40, "integrity": 300, "width": 2 },
    { "length": 3, "isReinforced": true, "name": "Reinforced DC Locker", "integrityFunctioningThreshold": 20, "height": 3, "damageThreshold": 35, "integrity": 200, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "CR70 Antenna", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 30, "integrity": 250, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "FR3300 Micro Reactor", "integrityFunctioningThreshold": 50, "height": 3, "damageThreshold": 30, "integrity": 200, "width": 3 },
    { "length": 8, "isReinforced": false, "name": "Mk610 Beam Turret", "integrityFunctioningThreshold": 30, "height": 8, "damageThreshold": 30, "integrity": 400, "width": 5 },
    { "length": 6, "isReinforced": false, "name": "Mk66 Cannon", "integrityFunctioningThreshold": 30, "height": 6, "damageThreshold": 30, "integrity": 350, "width": 3 },
    { "length": 8, "isReinforced": false, "name": "Mk68 Cannon", "integrityFunctioningThreshold": 30, "height": 8, "damageThreshold": 30, "integrity": 450, "width": 5 },
    { "length": 6, "isReinforced": false, "name": "Mk81 Railgun", "integrityFunctioningThreshold": 30, "height": 6, "damageThreshold": 30, "integrity": 300, "width": 3 },
    { "length": 8, "isReinforced": false, "name": "Mk82 Railgun", "integrityFunctioningThreshold": 30, "height": 8, "damageThreshold": 30, "integrity": 400, "width": 5 },
    { "length": 2, "isReinforced": false, "name": "RS35 'Frontline' Radar", "integrityFunctioningThreshold": 30, "height": 2, "damageThreshold": 30, "integrity": 200, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "RS41 'Spyglass' Radar", "integrityFunctioningThreshold": 30, "height": 2, "damageThreshold": 30, "integrity": 200, "width": 2 },
    { "length": 4, "isReinforced": false, "name": "Basic CIC", "integrityFunctioningThreshold": 10, "height": 6, "damageThreshold": 25, "integrity": 200, "width": 1 },
    { "length": 1, "isReinforced": false, "name": "Bulk Magazine", "integrityFunctioningThreshold": 10, "height": 1, "damageThreshold": 25, "integrity": 100, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Damage Control Central", "integrityFunctioningThreshold": 15, "height": 3, "damageThreshold": 25, "integrity": 125, "width": 1 },
    { "length": 5, "isReinforced": false, "name": "FM30X 'Prowler' Drive", "integrityFunctioningThreshold": 30, "height": 5, "damageThreshold": 25, "integrity": 200, "width": 3 },
    { "length": 3, "isReinforced": false, "name": "Small Workshop", "integrityFunctioningThreshold": 15, "height": 3, "damageThreshold": 25, "integrity": 75, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Auxiliary Steering", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 20, "integrity": 150, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Mk64 Cannon", "integrityFunctioningThreshold": 15, "height": 5, "damageThreshold": 20, "integrity": 225, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "Ammunition Elevators", "integrityFunctioningThreshold": 15, "height": 2, "damageThreshold": 15, "integrity": 100, "width": 2 },
    { "length": 1, "isReinforced": false, "name": "Berthing", "integrityFunctioningThreshold": 10, "height": 1, "damageThreshold": 15, "integrity": 50, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "CR10 Antenna", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 15, "integrity": 100, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "E15 'Masquerade' Signature Booster", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 15, "integrity": 100, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "E55 'Spotlight' Illuminator", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 15, "integrity": 75, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "E57 'Floodlight' Illuminator", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 15, "integrity": 75, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "E70 'Interruption' Jammer", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 15, "integrity": 100, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "E71 'Hangup' Jammer", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 15, "integrity": 75, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "E90 'Blanket' Jammer", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 15, "integrity": 75, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Energy Regulator", "integrityFunctioningThreshold": 15, "height": 3, "damageThreshold": 15, "integrity": 100, "width": 3 },
    { "length": 3, "isReinforced": false, "name": "ES22 'Pinard' Electronic Support Module", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 15, "integrity": 50, "width": 1 },
    { "length": 6, "isReinforced": false, "name": "Intelligence Center", "integrityFunctioningThreshold": 15, "height": 8, "damageThreshold": 15, "integrity": 200, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Large DC Locker", "integrityFunctioningThreshold": 10, "height": 6, "damageThreshold": 15, "integrity": 150, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "Mk20 'Defender' PDT", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 15, "integrity": 100, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "Mk25 'Rebound' PDT", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 15, "integrity": 100, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Mk61 Cannon", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 15, "integrity": 150, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Mk62 Cannon", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 15, "integrity": 150, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "Mk90 'Aurora' PDT", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 15, "integrity": 100, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "MLS-2 Launcher", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 15, "integrity": 100, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "MLS-3 Launcher", "integrityFunctioningThreshold": 10, "height": 5, "damageThreshold": 15, "integrity": 100, "width": 2 },
    { "length": 3, "isReinforced": false, "name": "Rapid DC Locker", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 15, "integrity": 70, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Small DC Locker", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 15, "integrity": 100, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "VLS1-23 Launcher", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 15, "integrity": 75, "width": 2 },
    { "length": 3, "isReinforced": false, "name": "VLS2-16 Launcher", "integrityFunctioningThreshold": 10, "height": 3, "damageThreshold": 15, "integrity": 100, "width": 4 },
    { "length": 2, "isReinforced": false, "name": "Actively Cooled Amplifiers", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 40, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "Adaptive Radar Receiver", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 40, "width": 2 },
    { "length": 3, "isReinforced": false, "name": "Analysis Annex", "integrityFunctioningThreshold": 15, "height": 3, "damageThreshold": 10, "integrity": 100, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Batlle Dressing Station", "integrityFunctioningThreshold": 15, "height": 3, "damageThreshold": 10, "integrity": 125, "width": 1 },
    { "length": 3, "isReinforced": false, "name": "Gun Plotting Center", "integrityFunctioningThreshold": 15, "height": 3, "damageThreshold": 10, "integrity": 100, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "Launcher Deluge System", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 75, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "Magazine Sprinklers", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 75, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "Mount Gyros", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 40, "width": 2 },
    { "length": 3, "isReinforced": false, "name": "Plant Control Center", "integrityFunctioningThreshold": 15, "height": 3, "damageThreshold": 10, "integrity": 100, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "Redundant Reactor Failsafes", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 75, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "Reinforced Thruster Nozzles", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 50, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "RF101 'Bullseye' Radar", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 70, "width": 1 },
    { "length": 2, "isReinforced": false, "name": "Signature Scrambler", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 50, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "Small Energy Regulator", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 75, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "Small Reactor Booster", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 40, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "Supplementary Radio Amplifiers", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 40, "width": 2 },
    { "length": 2, "isReinforced": false, "name": "Track Correlator", "integrityFunctioningThreshold": 10, "height": 2, "damageThreshold": 10, "integrity": 40, "width": 2 },
]